/**
 * StormLink seed data — populates every collection on first boot so the
 * dashboard feels alive out of the box.
 */
export const seedData = {
  companies: [
    {
      name: 'RigStorm Labs',
      slug: 'rigstorm-labs',
      description: 'Core tech arm — PC building, AI integration, digital innovation.',
      url: 'www.rigstormlabs.linkpc.net',
      goals: ['Ship the Atlas AI workstation', 'Launch StormForge tuning suite', 'Prototype edge AI kits'],
      accent: 'electric',
    },
    {
      name: 'RigStorm SiteMarket',
      slug: 'rigstorm-sitemarket',
      description: 'Marketplace for websites, domains, and hosting.',
      url: 'www.rigstormsitemarket.linkpc.net',
      goals: ['Relaunch marketplace v2', 'One-click hosting tiers', 'Domain auction beta'],
      accent: 'cyan',
    },
    {
      name: 'RigStorm LandAura',
      slug: 'rigstorm-landaura',
      description: 'Real estate listings and pricing strategies.',
      url: 'www.landaura.run.place',
      goals: ['Reach 1,000 active listings', 'Dynamic pricing engine', 'Regional market reports'],
      accent: 'emerald',
    },
    {
      name: 'RigStorm Zeyora',
      slug: 'rigstorm-zeyora',
      description: 'Delivery service app concept with full‑stack focus.',
      url: 'www.zeyora.run.place',
      goals: ['Ship courier MVP beta', 'Live order tracking', 'Driver onboarding flow'],
      accent: 'fuchsia',
    },
    {
      name: 'AdStorm',
      slug: 'adstorm',
      description: 'Digital marketing and brand growth strategies.',
      url: 'www.adstorm.run.place',
      goals: ['Double client base', 'Campaign automator v1', 'Growth analytics suite'],
      accent: 'amber',
    },
    {
      name: 'SkyED',
      slug: 'skyed',
      description: 'Professional branding agency for startup identity.',
      url: 'www.skyed.run.place',
      goals: ['10 startup identities', 'Brand kit generator', 'Design system library'],
      accent: 'sky',
    },
    {
      name: 'RigStorm Hub',
      slug: 'rigstorm-hub',
      description: 'Centralized innovation center connecting all ventures.',
      url: 'www.rigstormhub.run.place',
      goals: ['Unify SSO across ventures', 'Shared analytics layer', 'Internal comms portal'],
      accent: 'violet',
    },
  ],

  projects: [
    {
      name: 'Atlas AI Workstation',
      company: 'RigStorm Labs',
      description:
        'Flagship AI-ready workstation with integrated StormForge tuning and on-device inference benchmarks.',
      status: 'active',
      priority: 'high',
      owner: 'Lena Ortiz',
      dueDate: '2026-09-30',
      progress: 68,
      tags: ['AI', 'Hardware'],
    },
    {
      name: 'SiteMarket v2 Launch',
      company: 'RigStorm SiteMarket',
      description:
        'Full relaunch of the marketplace with new checkout, hosting tiers and streamlined domain flows.',
      status: 'active',
      priority: 'critical',
      owner: 'Kai Nakamura',
      dueDate: '2026-11-15',
      progress: 45,
      tags: ['Marketplace', 'Web'],
    },
    {
      name: 'LandAura Listing Engine',
      company: 'RigStorm LandAura',
      description:
        'Automated listing ingestion with dynamic pricing strategies tuned for regional markets.',
      status: 'review',
      priority: 'high',
      owner: 'Omar Haddad',
      dueDate: '2026-08-30',
      progress: 82,
      tags: ['Real Estate', 'API'],
    },
    {
      name: 'Zeyora Courier MVP',
      company: 'RigStorm Zeyora',
      description:
        'Delivery service concept app covering courier onboarding, live tracking and the full order flow.',
      status: 'planning',
      priority: 'medium',
      owner: 'Dev Patel',
      dueDate: '2026-12-01',
      progress: 20,
      tags: ['Delivery', 'Mobile'],
    },
    {
      name: 'AdStorm Campaign Automator',
      company: 'AdStorm',
      description: 'Multi-channel campaign builder with brand growth analytics and smart budget pacing.',
      status: 'active',
      priority: 'high',
      owner: 'Emma Lindqvist',
      dueDate: '2026-10-10',
      progress: 57,
      tags: ['Marketing', 'Automation'],
    },
    {
      name: 'SkyED Brand Kit Generator',
      company: 'SkyED',
      description: 'Identity toolkit that turns a startup brief into logos, palettes and brand guidelines.',
      status: 'completed',
      priority: 'medium',
      owner: 'Sofia Marek',
      dueDate: '2026-07-20',
      progress: 100,
      tags: ['Branding'],
    },
    {
      name: 'Hub Portal Unification',
      company: 'RigStorm Hub',
      description: 'Single portal and SSO layer connecting every RigStorm venture under one identity.',
      status: 'on-hold',
      priority: 'low',
      owner: 'Maya Storm',
      dueDate: '2027-01-15',
      progress: 35,
      tags: ['Platform', 'SSO'],
    },
  ],

  workflows: [
    {
      name: 'Atlas benchmarking suite',
      description: 'Automated inference benchmarks across StormForge builds.',
      stage: 'in-progress',
      company: 'RigStorm Labs',
      owner: 'Lena Ortiz',
      roles: ['AI', 'QA'],
      priority: 'high',
    },
    {
      name: 'SiteMarket checkout revamp',
      description: 'One-page checkout with hosting upsell path.',
      stage: 'in-progress',
      company: 'RigStorm SiteMarket',
      owner: 'Kai Nakamura',
      roles: ['Frontend', 'Backend'],
      priority: 'critical',
    },
    {
      name: 'LandAura pricing API',
      description: 'Dynamic pricing endpoints powered by regional comps.',
      stage: 'review',
      company: 'RigStorm LandAura',
      owner: 'Omar Haddad',
      roles: ['Backend', 'Product'],
      priority: 'high',
    },
    {
      name: 'Zeyora driver onboarding',
      description: 'KYC, vehicle documents and shift selection flow.',
      stage: 'backlog',
      company: 'RigStorm Zeyora',
      owner: 'Dev Patel',
      roles: ['Mobile', 'Design'],
      priority: 'medium',
    },
    {
      name: 'Hub SSO integration',
      description: 'Unified identity across all RigStorm applications.',
      stage: 'backlog',
      company: 'RigStorm Hub',
      owner: 'Maya Storm',
      roles: ['DevOps', 'Backend'],
      priority: 'high',
    },
    {
      name: 'SkyED identity templates',
      description: 'Reusable brand templates for startup identity kits.',
      stage: 'done',
      company: 'SkyED',
      owner: 'Sofia Marek',
      roles: ['Design'],
      priority: 'medium',
    },
    {
      name: 'AdStorm analytics dashboard',
      description: 'Campaign KPIs with growth attribution views.',
      stage: 'in-progress',
      company: 'AdStorm',
      owner: 'Emma Lindqvist',
      roles: ['Frontend', 'Product'],
      priority: 'medium',
    },
    {
      name: 'SiteMarket hosting migration',
      description: 'Move legacy customer sites onto the new hosting grid.',
      stage: 'done',
      company: 'RigStorm SiteMarket',
      owner: 'Kai Nakamura',
      roles: ['DevOps'],
      priority: 'high',
    },
  ],

  products: [
    {
      name: 'StormForge PC',
      company: 'RigStorm Labs',
      description: 'AI-tuned workstation line with StormForge orchestration built in.',
      status: 'active',
      version: 'v2.4',
      owner: 'Lena Ortiz',
      progress: 74,
    },
    {
      name: 'LinkHost Starter',
      company: 'RigStorm SiteMarket',
      description: 'Entry hosting bundle with one-click site templates.',
      status: 'active',
      version: 'v1.8',
      owner: 'Kai Nakamura',
      progress: 60,
    },
    {
      name: 'AuraList',
      company: 'RigStorm LandAura',
      description: 'Listing management suite with pricing intelligence.',
      status: 'beta',
      version: 'v0.9',
      owner: 'Omar Haddad',
      progress: 88,
    },
    {
      name: 'Zeyora Runner',
      company: 'RigStorm Zeyora',
      description: 'Courier companion app for deliveries and smart routing.',
      status: 'alpha',
      version: 'v0.3',
      owner: 'Dev Patel',
      progress: 30,
    },
    {
      name: 'BrandStorm Kit',
      company: 'SkyED',
      description: 'Startup identity packages: logo, palette and voice.',
      status: 'active',
      version: 'v1.2',
      owner: 'Sofia Marek',
      progress: 52,
    },
    {
      name: 'StormPulse Analytics',
      company: 'AdStorm',
      description: 'Brand growth measurement across AdStorm campaigns.',
      status: 'concept',
      version: 'v0.1',
      owner: 'Emma Lindqvist',
      progress: 15,
    },
  ],

  goals: [
    {
      title: 'Launch SiteMarket v2 by Q4',
      company: 'RigStorm SiteMarket',
      description: 'Relaunch the marketplace with checkout, domains and hosting.',
      progress: 45,
      status: 'on-track',
      dueDate: '2026-11-15',
    },
    {
      title: 'Ship Zeyora MVP beta',
      company: 'RigStorm Zeyora',
      description: 'Deliver a closed beta of the courier app to 50 drivers.',
      progress: 25,
      status: 'on-track',
      dueDate: '2026-12-01',
    },
    {
      title: 'Reach 1,000 LandAura listings',
      company: 'RigStorm LandAura',
      description: 'Grow the listing engine to full regional coverage.',
      progress: 62,
      status: 'on-track',
      dueDate: '2026-09-30',
    },
    {
      title: 'Unify ventures under RigStorm Hub',
      company: 'RigStorm Hub',
      description: 'One portal, one identity for every RigStorm company.',
      progress: 38,
      status: 'at-risk',
      dueDate: '2027-01-15',
    },
    {
      title: 'Double AdStorm client base',
      company: 'AdStorm',
      description: 'Scale campaigns with the new automator and growth reports.',
      progress: 55,
      status: 'on-track',
      dueDate: '2026-10-31',
    },
    {
      title: '10 startup identities for SkyED',
      company: 'SkyED',
      description: 'Portfolio milestone for the branding agency.',
      progress: 70,
      status: 'on-track',
      dueDate: '2026-09-15',
    },
  ],

  members: [
    { name: 'Maya Storm', role: 'Product Lead', company: 'RigStorm Hub', focus: 'Cross-venture strategy & roadmap' },
    { name: 'Arjun Vey', role: 'Frontend Engineer', company: 'RigStorm Labs', focus: 'Dashboard UI & visualization' },
    { name: 'Lena Ortiz', role: 'AI Engineer', company: 'RigStorm Labs', focus: 'StormForge tuning & inference' },
    { name: 'Kai Nakamura', role: 'Backend Engineer', company: 'RigStorm SiteMarket', focus: 'Marketplace & hosting APIs' },
    { name: 'Sofia Marek', role: 'Design Lead', company: 'SkyED', focus: 'Brand systems & identity' },
    { name: 'Dev Patel', role: 'Full-Stack Developer', company: 'RigStorm Zeyora', focus: 'Delivery app & logistics' },
    { name: 'Emma Lindqvist', role: 'Growth Strategist', company: 'AdStorm', focus: 'Campaigns & brand growth' },
    { name: 'Omar Haddad', role: 'Real Estate Analyst', company: 'RigStorm LandAura', focus: 'Pricing strategy & comps' },
    { name: 'Ivy Chen', role: 'QA Engineer', company: 'RigStorm Hub', focus: 'Release quality & automation' },
  ],

  notifications: [
    {
      title: 'Welcome to StormLink',
      message: 'The RigStorm command center is live. Explore your dashboard, projects and workflows.',
      type: 'announcement',
      read: false,
    },
    {
      title: 'LandAura Listing Engine in review',
      message: 'The pricing API passed QA and is ready for final review.',
      type: 'milestone',
      read: false,
    },
    {
      title: 'SiteMarket v2 checkpoint',
      message: 'Checkout revamp is 45% complete — on track for the Q4 launch.',
      type: 'update',
      read: true,
    },
    {
      title: 'New team member',
      message: 'Ivy Chen joined RigStorm Hub as QA Engineer.',
      type: 'team',
      read: true,
    },
  ],
};

/** Seed every collection that is still empty. */
export async function seedStore(store) {
  let seeded = 0;
  for (const [name, docs] of Object.entries(seedData)) {
    if (!store[name]) continue;
    if ((await store[name].count()) === 0) {
      for (const doc of docs) await store[name].create(doc);
      seeded += docs.length;
    }
  }
  if (seeded > 0) console.log(`[stormlink] Seeded ${seeded} starter records`);
  return seeded;
}
